name: Sync to Hugging Face

on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        uses: nateraw/huggingface-sync-action@v0.0.5
        with:
          github_repo_id: Vishesh193/InsureAI
          huggingface_repo_id: aroravishesh/insure-ai
          hf_token: ${{ secrets.HF_TOKEN }}
